// Sync compiled ABIs into the frontend.
//
// Reads contracts/artifacts/src/*.sol/*.json (Hardhat's compile
// output — gitignored) and writes the .abi arrays as `as const`
// TypeScript exports under src/lib/contracts/abi/ (which IS tracked
// in git, so the frontend has stable ABI snapshots without depending
// on the contracts subproject being built).
//
// Run after a contract change:
//   cd contracts && npm run compile && node scripts/sync-abi.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../..");
const artifactsDir = resolve(__dirname, "../artifacts/src");
const outDir = resolve(repoRoot, "src/lib/contracts/abi");

const sources = [
  ["MockUSDC", "mockUsdcAbi"],
  ["CoverFiPolicy", "coverFiPolicyAbi"],
];

for (const [name, exportName] of sources) {
  const json = JSON.parse(
    readFileSync(join(artifactsDir, `${name}.sol/${name}.json`), "utf8"),
  );
  const header =
    `/**\n` +
    ` * ABI for ${name}.\n` +
    ` *\n` +
    ` * AUTOGENERATED from contracts/artifacts/src/${name}.sol/${name}.json\n` +
    ` * (Hardhat compile output of contracts/src/${name}.sol). \`as const\` is\n` +
    ` * load-bearing — viem's type inference walks the literal to derive\n` +
    ` * function / event / error signatures, which is why this file lives\n` +
    ` * here as TypeScript rather than as a raw JSON re-export.\n` +
    ` *\n` +
    ` * To refresh: rerun contracts/scripts/sync-abi.mjs after recompiling.\n` +
    ` */\n`;
  const out =
    header +
    `\nexport const ${exportName} = ${JSON.stringify(json.abi, null, 2)} as const;\n`;
  const outPath = join(outDir, `${name}.ts`);
  writeFileSync(outPath, out);
  console.log(`wrote ${outPath} — ${json.abi.length} entries`);
}
